theme = "bogster_light"

[editor]
gutters = ["diagnostics", "spacer"]
auto-completion = false
auto-format = false
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"

[editor.whitespace.characters]
space = "·"

[editor.file-picker]
hidden = false

[keys.insert]
C-x = "normal_mode"
C-space = "completion"
