theme = "snazzy"

[editor]
gutters = ["diagnostics", "spacer"]
auto-completion = false
auto-format = false
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "position"]
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.whitespace.render]
space = "all"

[editor.whitespace.characters]
space = "·"

[editor.file-picker]
hidden = false

[keys.normal]
X = "extend_line_above"
C-u = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
C-d = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
"{" = ["goto_prev_paragraph", "move_visual_line_up", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
D = ["collapse_selection", "select_mode", "goto_line_end", "delete_selection"]
 
[keys.insert]
C-x = "normal_mode"
C-space = "completion"
